[package]
name = "bulletproof"
version = "1.1.2"
authors = [
    "Omer Shlomovits <omer@kzencorp.com>",
    "Suyash Bagad <suyashnbagad1997@gmail.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
curv = { git = "https://github.com/survived/curv.git" , branch = "expose-testing-macro" }

itertools = "0.7.8"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
criterion = "0.2"
curv = { git = "https://github.com/survived/curv.git" , branch = "expose-testing-macro", features = ["testing-utils"] }

[[bench]]
name = "range_proof"
path = "benches/range_proof.rs"
harness = false
